# FrontEnd
FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80

#BackEnd

FROM node:18-alpine

WORKDIR /app

RUN npm init -y && \
    npm install express pg cors

COPY app.js .

EXPOSE 3000

CMD ["node", "app.js"]