version: '3'
services:
  database:
    image: postgres:14-alpine
    container_name: app_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
  backend:
    build: ./backend
    container_name: app_backend
    depends_on:
      - database
    ports:
      - "3000:3000"
    networks:
      - app_network
  frontend:
    build: ./frontend
    container_name: app_frontend
    depends_on:
      - backend
    ports:
      - "4000:80"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge